/* Lista de invitados. Generada desde "invitados y pases.xlsx".
   Cada codigo es el que viaja en el enlace: ?i=codigo */
window.INVITADOS = {
  "jose-pedro": { n: "Sr. José Pedro Román Paladines y Esposa", p: 2 },
  "sofia-encarnacion": { n: "Sra. Sofia Encarnación", p: 1 },
  "alex-ortega": { n: "Sr. Alex Ortega y Familia", p: 5 },
  "cecibel-ortega": { n: "Sra. Cecibel Ortega y Familia", p: 3 },
  "mauricio-roman": { n: "Sr. Mauricio Román y Familia", p: 3 },
  "edwin-roman": { n: "Sr. Edwin Román", p: 1 },
  "carlos-roman": { n: "Sr. Carlos Román", p: 1 },
  "jordan-roman": { n: "Sr. Jordan Román", p: 1 },
  "franco-roman": { n: "Sr. Franco Román y Esposa", p: 2 },
  "victor-largo": { n: "Sr. Victor Largo y Familia", p: 3 },
  "angel-maldonado": { n: "Sr. Angel Maldonado y Esposa", p: 2 },
  "angel-encarnacion": { n: "Sr. Angel Encarnación y Esposa", p: 2 },
  "jose-encarnacion": { n: "Sr. José Encarnación y Esposa", p: 2 },
  "sara-encarnacion": { n: "Sra. Sara Encarnación", p: 1 },
  "juan-paladines": { n: "Sr. Juan Paladines y Esposa", p: 2 },
  "margarita-paladines": { n: "Sra Margarita Paladines e Hija", p: 2 },
  "jimmy-encarnacion": { n: "Ing. Jimmy Encarnación", p: 1 },
  "eduardo-roman": { n: "Ing. Eduardo Román y Esposa", p: 2 },
  "carlos-herrera": { n: "Ing. Carlos Herrera y Esposa", p: 2 },
  "jandry-granda": { n: "Ing. Jandry Granda y Esposa", p: 2 },
  "jorge-maldonado": { n: "Sr. Jorge Maldonado y Familia", p: 4 },
  "manrique-encarnacion": { n: "Abg. Manrique Encarnación", p: 1 },
  "brailyn-encarnacion": { n: "Dr. Brailyn Encarnación", p: 1 },
  "jonathan-encarnacion": { n: "Lcd. Jonathan Encarnación y Esposa", p: 2 },
  "edgar-rivera": { n: "Sr. Edgar Rivera y Esposa", p: 2 },
  "paul-rivera": { n: "Sr. Paul Rivera y Esposa", p: 2 },
  "ramiro-cordova": { n: "Sr. Ramiro Córdova y Esposa", p: 2 },
};
